### ISSUE TITLE
kimage

### ISSUE THREAD

**Issue by agombert** [alsoltani/Dataviz#1]
![kfet](https://cloud.githubusercontent.com/assets/17645711/14050893/3ee88f3c-f2bf-11e5-9195-5e4b7ece4f9b.jpg)

**Comment by MorganSchmitz** [comment]
Bon, Gombert, je crois qu'on a fait le tour du sujet.

**Comment by agombert** [comment]
pas compris ?

2016-07-22 11:45 GMT+02:00 MorganSchmitz notifications@github.com:

**Comment by MorganSchmitz** [comment]
https://youtu.be/FzUxqmQuE5c

(pardon)

**Comment by agombert** [comment]
Hahaha

2016-07-22 11:50 GMT+02:00 MorganSchmitz notifications@github.com:
